apiVersion: v1
kind: Pod
metadata:
  name: configmap
  labels:
    name: expence
spec:
  containers:
  - name: nginx
    image: nginx
    envfrom: 
    - configMapRef:
        name: configmap
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
