apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:  # to encode the userand and password we use " echo username | base64 "
  username: cmFrZXNoCg==    
  password: cmFrZXNoQDEyMwo=

