apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
    name: frontend
    project: expense
    component: frontend
    environment: dev
  ports:
  - port: 80
    targetPort: 80 
