apiVersion: apps/v1
kind: ReplicatSet 
metadata:
  name: raplicaset
  labels:
    app: nginx
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
       tier: frontend
       app: nginx
  template:
    metadata:
      name: replicaset
      labels:
        app: nginx
        tier: frontend
        project: expence
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080
